[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # whitespace
    "W",
    # list comprehensions
    "C4",
    # Code simplification
    "SIM",
    # Type checking
    "TCH"
]
