name: migrator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Install library
        run: poetry install

      - name: Unit Tests
        run: |
          poetry run python -m unittest discover .

      - name: Lint
        uses: chartboost/ruff-action@v1

      - name: Format
        uses: chartboost/ruff-action@v1
        with:
          args: format --check
