name: migrator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Unit Tests
        run: |
          python -m unittest discover .

      - name: Lint
        uses: chartboost/ruff-action@v1

